git:
  submodules: false
language: scala
# run on new infrastructure
sudo: false
cache:
  apt: true
  directories:
    $HOME/.ivy2
    regression/install
    emulator/verilator

# packages needed to build riscv-tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - device-tree-compiler
      - libusb-1.0-0-dev


# blacklist private branches
branches:
  except:
    - hwacha
    - boom
    - /^hurricane.*$/

jobs:
  include:
    - stage: prepare cache
      script:
        - make tools verilator -C regression SUITE=none
      before_install:
        - export CXX=g++-4.8 CC=gcc-4.8
      before_cache:
        - ls -t regression/install | tail -n+2 | sed s@^@regression/install/@ | xargs rm -rf
    - &test
      stage: Test
      script:
        - travis_wait 30 make emulator-ndebug -C regression SUITE=RocketSuiteA JVM_MEMORY=3G
        - travis_wait 30 make emulator-regression-tests -C regression SUITE=RocketSuiteA JVM_MEMORY=3G
    - <<: *test
      script:
        - travis_wait 30 make emulator-ndebug -C regression SUITE=RocketSuiteB JVM_MEMORY=3G
        - travis_wait 30 make emulator-regression-tests -C regression SUITE=RocketSuiteB JVM_MEMORY=3G
    - <<: *test
      script:
        - travis_wait 30 make emulator-ndebug -C regression SUITE=RocketSuiteC JVM_MEMORY=3G
        - travis_wait 30 make emulator-regression-tests -C regression SUITE=RocketSuiteC JVM_MEMORY=3G
    - <<: *test
      script:
        - travis_wait 30 make emulator-ndebug -C regression SUITE=GroundtestSuite JVM_MEMORY=3G
        - travis_wait 30 make emulator-regression-tests -C regression SUITE=GroundtestSuite JVM_MEMORY=3G
    - <<: *test
      script:
        - travis_wait 60 make emulator-ndebug -C regression SUITE=UnittestSuite JVM_MEMORY=3G
        - travis_wait 30 make emulator-regression-tests -C regression SUITE=UnittestSuite JVM_MEMORY=3G

